package apps;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public abstract class TC extends Task {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

//        System.out.println(new TC().getGreeting());
    }
}
