package apps;

import obj.Vertex;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// FixMe: Assume all tasks are in memory
// FixMe: Worry about canonicality later.
public class TC extends Task {

    boolean isDone;
    Vertex seed;
//  FixME: Shound be a array not a list
    int agg=0;

    public TC(Vertex vid){
        super(vid);
        seed = vid;
    }
//  FixMe: Remove duplicates in to Fetch
    @Override
    public void compute() {
        if(step==0){
            refreshToFetch();
            for(int i:seed.getNeighbours()){
                addToFetch(i);
            }
            step=step+1;
            return;
        }
        if(step==1){
            refreshToFetch();
            for(Vertex v:exploredVertices.get(step)){
                for(int i:v.getNeighbours()){
                    addToFetch(i);
                }
            }
            step = step+1;
            return;
        }
        if(step == 2){
            for(Vertex v:exploredVertices.get(step)){
                for(int i:v.getNeighbours()){
                    if(i==seed.getVertexId()){
                        agg++;
                    };
                }

            }
            isDone = true;
            return;
        }
    }

    @Override
    public boolean allDone() {
        return isDone;
    }

    @Override
    public int getAgg() {
        return agg;
    }


}
