/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class AppTest {

    @Test public void testAppHasAGreeting() {
        Graph graph = new DefaultGraph();
        Driver driver = new Driver(graph);
        driver.run();
        System.out.println("Loading a graph");
    }
}
